openapi: 3.0.2
info:
  title: games-api
  version: 1.0.0
  description: A simple API to manage a list of games.
paths:
  /games:
    get:
      summary: Gets a list of games
      description: Returns a list of all games.
      tags:
        - games
      responses:
        '200':
          description: A list of games.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
              example:
                - id: 1
                  name: "Witcher 3"
                  price: 29.99
                - id: 2
                  name: "Cyberpunk 2077"
                  price: 59.99
    post:
      summary: Creates a new game
      description: Adds a new game to the list.
      tags:
        - games
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGame'
      responses:
        '21_CREATED':
          description: The created game.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: One or all params are missing
  '/games/{id}':
    get:
      summary: Get full details of a game
      description: Returns full details of a given id game.
      tags:
        - games
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the game to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: Full details of a given game.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: Return error when no game is found.
    delete:
      summary: Deletes a game
      description: Deletes a game by its ID.
      tags:
        - games
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the game to delete.
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '404':
          description: Game not found
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
      example:
        id: 1
        name: "Witcher 3"
        price: 29.99
    NewGame:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        price:
          type: number
          format: float
      example:
        name: Tetris
        price: 0.99